/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Çağdaş Sert
 */
public class girisekran extends javax.swing.JFrame {
    
    Connection conn = null; PreparedStatement pst=null; ResultSet rs=null;
    private Object sifre;

    /**
     * Creates new form odev5
     */
    public girisekran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_girisyap = new javax.swing.JButton();
        btn_kayitol = new javax.swing.JButton();
        txt_tckimlikhasta = new javax.swing.JTextField();
        txt_sifrehasta = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kayitoldoktor = new javax.swing.JButton();
        txt_tckimlikdoktor = new javax.swing.JTextField();
        txt_sifredoktor = new javax.swing.JPasswordField();
        btn_girisyapdoktor1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HASTANE RANDEVU SİSTEMİNE HOŞ GELDİNİZ ");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("T.C KİMLİK NO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 137, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ŞİFRE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 150, 54, 22);

        btn_girisyap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_girisyap.setText("GİRİŞ YAP");
        btn_girisyap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn_girisyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisyapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_girisyap);
        btn_girisyap.setBounds(330, 235, 134, 44);

        btn_kayitol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kayitol.setText("KAYIT OL");
        btn_kayitol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn_kayitol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitolActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kayitol);
        btn_kayitol.setBounds(130, 235, 124, 44);

        txt_tckimlikhasta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(txt_tckimlikhasta);
        txt_tckimlikhasta.setBounds(210, 80, 190, 30);

        txt_sifrehasta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txt_sifrehasta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_sifrehasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifrehastaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sifrehasta);
        txt_sifrehasta.setBounds(210, 140, 190, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uDGj34.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1, -4, 620, 300);

        jTabbedPane1.addTab("HASTA GİRİŞ", jPanel1);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("T.C KİMLİK NO");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 80, 137, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ŞİFRE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 150, 54, 22);

        btn_kayitoldoktor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_kayitoldoktor.setText("KAYIT OL");
        btn_kayitoldoktor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btn_kayitoldoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitoldoktorActionPerformed(evt);
            }
        });
        jPanel2.add(btn_kayitoldoktor);
        btn_kayitoldoktor.setBounds(80, 230, 175, 46);

        txt_tckimlikdoktor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_tckimlikdoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tckimlikdoktorActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tckimlikdoktor);
        txt_tckimlikdoktor.setBounds(210, 80, 190, 31);

        txt_sifredoktor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(txt_sifredoktor);
        txt_sifredoktor.setBounds(210, 140, 190, 36);

        btn_girisyapdoktor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_girisyapdoktor1.setText("GİRİŞ YAP");
        btn_girisyapdoktor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btn_girisyapdoktor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisyapdoktor1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_girisyapdoktor1);
        btn_girisyapdoktor1.setBounds(300, 230, 175, 46);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uDGj34.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 619, 290);

        jTabbedPane1.addTab("DOKTOR GİRİŞİ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisyapActionPerformed
        
        try
        {
          conn=veritabani.connect_db();  
          String sql="SELECT * FROM HASTATABLOSU WHERE HASTATC='"+txt_tckimlikhasta.getText()+
                     "' AND HASTASİFRE='"+txt_sifrehasta.getText()+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          if(rs.next()){
             JOptionPane.showMessageDialog(null, "Giriş Başarılı ! ");
             hastarandevual Frame =new hastarandevual();
             Frame.setVisible(true);
             this.setVisible(false);
          }
          else
          {
             JOptionPane.showMessageDialog(null, "Girdiğiniz Kullanıcı adı veya Şifre Hatalı ! ");
          }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }    
           finally{
            try{
                conn.close();
            }
            catch(Exception ex)
            {
                
            } 
        }
            
            
        
    }//GEN-LAST:event_btn_girisyapActionPerformed

    private void btn_kayitolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitolActionPerformed
        hastakayit AL=new hastakayit();
        AL.setVisible(true);
        
    }//GEN-LAST:event_btn_kayitolActionPerformed

    private void txt_tckimlikdoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tckimlikdoktorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tckimlikdoktorActionPerformed

    private void btn_kayitoldoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitoldoktorActionPerformed
doktorkayit Frame =new doktorkayit();
             Frame.setVisible(true);
             this.setVisible(false);    
    }//GEN-LAST:event_btn_kayitoldoktorActionPerformed

    private void txt_sifrehastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifrehastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sifrehastaActionPerformed

    private void btn_girisyapdoktor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisyapdoktor1ActionPerformed
try
        {
          conn=veritabani.connect_db();  
          String sql="SELECT * FROM DOKTORTABLOSU WHERE DOKTORTC='"+txt_tckimlikdoktor.getText()+
                     "' AND DOKTORSİFRE='"+txt_sifredoktor.getText()+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          if(rs.next()){
             JOptionPane.showMessageDialog(null, "Giriş Başarılı ! ");
             randevularim Frame =new randevularim();
             Frame.setVisible(true);
             this.setVisible(false);
          }
          else
          {
             JOptionPane.showMessageDialog(null, "Girdiğiniz Kullanıcı adı veya Şifre Hatalı ! ");
          }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }    
           finally{
            try{
                conn.close();
            }
            catch(Exception ex)
            {
                
            } 
        }        

    }//GEN-LAST:event_btn_girisyapdoktor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_girisyap;
    private javax.swing.JButton btn_girisyapdoktor1;
    private javax.swing.JButton btn_kayitol;
    private javax.swing.JButton btn_kayitoldoktor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField txt_sifredoktor;
    private javax.swing.JPasswordField txt_sifrehasta;
    private javax.swing.JTextField txt_tckimlikdoktor;
    private javax.swing.JTextField txt_tckimlikhasta;
    // End of variables declaration//GEN-END:variables

    private static class jtex_tckimlik1 {

        private static Object getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jtex_tckimlik1() {
        }
    }
}
